### ISSUE TITLE
Amortization(0).payment returns nil not zero

### ISSUE THREAD

**Issue by mstahl** [bcsgsvn/finance#29]
The #payment method should be guaranteed to return a number, as 1) methods that depend on it are almost certainly expecting a number; and 2) if having an amount of zero is unrecoverable an exception should be thrown instead of returning nil, as returning nil is ambiguous.

**Comment by marksweston** [comment]
@mstahl @tubedude is this issue still open?

**Comment by mstahl** [comment]
Yeah I don't even work at the company I was working at when I filed this so I'm gonna close it.
